name: Cron Example

on:
  # schedule:
  #   - cron: "* * * * *"
  workflow_dispatch:

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cron-example

    steps:
      - uses: actions/checkout@v2

      # Setup Nodejs
      - name: Setup Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      # Install Yarn
      - name: Install Yarn 
        run: npm install -global yarn

      # Install libraries
      - name: install dependencies
        run: yarn install --frozen-lockfile

      # Run tests
      - name: Run test
        run: yarn test